###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Deadlift",
    "reps": 20,
    "weight": 200,
    "units": "lbs",
    "date": "08-11-21"
}

###
GET http://localhost:3000/exercises HTTP/1.1


###

PUT http://localhost:3000/exercises/61139066b1c12c38e05eab7b HTTP/1.1
content-type: application/json

{
    "name": "Deadlift",
    "reps": 15,
    "weight": 200,
    "units": "lbs",
    "date": "08-11-21"
}

###
DELETE http://localhost:3000/exercises/61138da07fd21d2834c8aeb8 HTTP/1.1


###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Squats",
    "reps": 22,
    "weight": 220,
    "units": "lbs",
    "date": "08-12-21"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Bench Press",
    "reps": 10,
    "weight": 300,
    "units": "lbs",
    "date": "08-11-21"
}

###
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Shoulder Press",
    "reps": 12,
    "weight": 100,
    "units": "lbs",
    "date": "07-11-21"
}
